version: "3.8"

services:
  app:
    build: .
    container_name: wise-catalog
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB=local
      - SERVER_PORT=8080
      - JWT_SECRET=my-secret-key
    depends_on:
      - redis
      - mongodb

  redis:
    image: redis:7
    container_name: redis-server
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  redis_data:
  mongo_data: