spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DB:local}
server:
  port: ${SERVER_PORT:8080}

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}